### ISSUE TITLE
I can't build and run 

### ISSUE THREAD

**Issue by doanhbui** [bcgit/bc-kotlin#13]
Dear Pro,
I am Doanh, I am a newbie of cryptography industries. I am learning and try this project using Kotlin, but I can't run and build.
My environment is: 

- Kotlin version 1.7.21 (JRE 18.0.2-ea+9-Ubuntu-222.04)
- Gradle version 6.8
and I got issue on bellow, please help me to resolve and guide me how to test and run code of this project.

Thank you so much.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kcrypto:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by primetomas** [comment]
Hi, I recently re-installed on Ubuntu 22.04 and had issues with Gradle, but not Kotlin.

For me: 
>kotlinc -version
info: kotlinc-jvm 1.7.21 (JRE 11.0.20+8-post-Ubuntu-1ubuntu122.04)

How do you install the components?

What is the full error you get when doing "gradle build"?

Did you copy BC jars into the bc-jars-req directory? bcprov, bcpkix and bcutil are needed there.

**Comment by doanhbui** [comment]
> Hi, I recently re-installed on Ubuntu 22.04 and had issues with Gradle, but not Kotlin.
> 
> For me:
> 
> > kotlinc -version
> > info: kotlinc-jvm 1.7.21 (JRE 11.0.20+8-post-Ubuntu-1ubuntu122.04)
> 
> How do you install the components?
> 
> What is the full error you get when doing "gradle build"?
> 
> Did you copy BC jars into the bc-jars-req directory? bcprov, bcpkix and bcutil are needed there.
Hi @primetomas,
Thanks for your reply, I just build successful, last time I copied not full bc jars file.

**Comment by dghgit** [comment]
I've added a check which should print an error message if the bc-reg-jars directory is empty now. 

With the latest updates you'll need to update what is in bc-reg-jars with the latest beta to get it to work correctly - the OIDs for Dilithium as well as some other PQC related details have changed with the release of the draft FIPS standards. 

The beta is available at https://www.bouncycastle.org/betas

**Comment by jjzl** [comment]
Hello everyone,

I am writing to ask for your help. 

I am learning about cryptography and I am trying to create a hybrid certificate following the video "Post-Quantum Cryptography – Create Hybrid Certificates using Bouncy Castle Kotlin", and I am getting the following error:

Exception in thread "main" java.lang.IllegalArgumentException: unknown parameter name: MLDSA2
        at org.bouncycastle.jcajce.spec.MLDSAParameterSpec.fromName(Unknown Source)
        at KCryptoServices$Companion.signingKeyPair(KCryptoServices.kt:121)
        at org.bouncycastle.kcrypto.dsl.SigningKeyBuilder.signingKeyPair(KCryptoServicesDsl.kt:26)
        at org.bouncycastle.kcrypto.dsl.KCryptoServicesDslKt.signingKeyPair(KCryptoServicesDsl.kt:46)
        at MakeDualCertificateAndDualCrlKt.main(MakeDualCertificateAndDualCrl.kt:24)
        at MakeDualCertificateAndDualCrlKt.main(MakeDualCertificateAndDualCrl.kt)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:70)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:183)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:193)

The command I am running is:

kotlin -cp ../kcrypto/build/libs/bc-kcrypto-0.0.9.jar:../bc-jars-reg/bcprov-jdk18on-1.79.jar:../bc-jars-reg/bcpkix-jdk18on-1.79.jar:../bc-jars-reg/bcutil-jdk18on-1.79.jar:../examples/build/classes/kotlin/main MakeDualCertificateAndDualCrlKt

For me:

kotlinc-jvm 2.0.21 (JRE 11.0.25+9-post-Ubuntu-1ubuntu124.04)
Kotlin version 2.0.21-release-482 (JRE 11.0.25+9-post-Ubuntu-1ubuntu124.04)
Gradle 7.4


Could you please comment on what I could be doing wrong?

Best regards

**Comment by dghgit** [comment]
Sorry, it's a typo in the script. It's now fixed on GitHub.

**Comment by jjzl** [comment]
Thanks for your reply, I confirm that I was already able to create the hybrid certificate.

Best regards
